name: mustadam
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  ## t2 -- Presentation
  flutter_svg: ^2.0.5
  url_launcher: ^6.3.1
  barcode_scan2: ^4.5.1
  image_picker: ^1.1.2
  ## t2 -- Providers
  cloud_firestore: ^5.6.0
  firebase_database: ^11.0.2
  firebase_messaging: ^15.2.4
  #  qr_code_scanner: ^1.0.1
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  firebase_storage: ^12.4.4
  http: ^0.13.0
  ## t2 -- Services
  flutter_dotenv: ^5.0.2
  logger: ^2.5.0
  min_id: ^1.1.0
  video_player: ^2.9.5
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  font_awesome_flutter: ^10.8.0
  #  firebase_crashlytics: ^4.1.3
  form_controller: ^0.8.4
  google_fonts: ^4.0.4
  awesome_notifications: ^0.10.1
  ## t2 -- Firebase
  firebase: ^9.0.2
  firebase_auth: ^5.3.1
  #  firebase_storage: ^11.2.1
  permission_handler: ^11.3.1
  ## t2 -- Other Utilities
  multi_dropdown: ^3.0.0
  qr_flutter: ^4.0.0
  timelines_plus: ^1.0.4
  google_sign_in: ^6.2.2
  ##!SECTION --Development Dependencies
  stack_trace: any
  firebase_core: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_application_id: ^2.0.0-dev
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
